on load:
    if {skripts::*} contains "core.sk" and "bck_manager.sk":
        send "§6[§4BCK§6]§r Loading language..." to console
        send "§6[§4BCK§6/§b§lLanguage§6]§r Loaded successfully !" to console
        load yaml "plugins/Skript/scripts/BCK/manager/language/config.yml" as "bck.manager.language.config"
        load yaml "plugins/Skript/scripts/BCK/manager/language/data.yml" as "bck.manager.language.data"
    else:
        broadcast "§6[§4BCK§6/§b§lLanguage§6]§r Script loading cancel It requires (§lcore.sk§r and §lbck_manager.sk§r)"
        unload script file "bck_language.sk"