on load:
	send "§6[§4BCK§6]§r Installing core..." to console
	send "§6[§4BCK§6]§r Installing manager..." to console
	send "§6[§4BCK§6]§r Setup..." to console
	set {_link} to "https://raw.githubusercontent.com/Blaackknight/BCK/main/BCK"
	create script "plugins/Skript/scripts/BCK/manager/temp.txt"
	delete file "plugins/Skript/scripts/BCK/manager/temp.txt"
	create script "plugins/Skript/scripts/BCK/core/temp.txt"
	delete file "plugins/Skript/scripts/BCK/core/temp.txt"
	create script "plugins/Skript/scripts/BCK/manager/money/temp.txt"
	delete file "plugins/Skript/scripts/BCK/manager/money/temp.txt"
	create script "plugins/Skript/scripts/BCK/manager/account/temp.txt"
	delete file "plugins/Skript/scripts/BCK/manager/account/temp.txt"
	create script "plugins/Skript/scripts/BCK/manager/clan/temp.txt"
	delete file "plugins/Skript/scripts/BCK/manager/clan/temp.txt"
	create script "plugins/Skript/scripts/BCK/manager/contener/temp.txt"
	delete file "plugins/Skript/scripts/BCK/manager/contener/temp.txt"
	create script "plugins/Skript/scripts/BCK/manager/elevator/temp.txt"
	delete file "plugins/Skript/scripts/BCK/manager/elevator/temp.txt"
	create script "plugins/Skript/scripts/BCK/manager/hammer/temp.txt"
	delete file "plugins/Skript/scripts/BCK/manager/hammer/temp.txt"
	wait 5 tick
	download file from "%{_link}%/core/core.sk" to file "plugins/Skript/scripts/BCK/core/core.sk"
	download file from "%{_link}%/core/core_functions.sk" to file "plugins/Skript/scripts/BCK/core/core_functions.sk"
	download file from "%{_link}%/core/config.yml" to file "plugins/Skript/scripts/BCK/core/config.yml"

	download file from "%{_link}%/manager/bck_manager.sk" to file "plugins/Skript/scripts/BCK/manager/bck_manager.sk"
	download file from "%{_link}%/manager/bck_manager_debug.sk" to file "plugins/Skript/scripts/BCK/manager/bck_manager_debug.sk"
	download file from "%{_link}%/manager/config.yml" to file "plugins/Skript/scripts/BCK/manager/config.yml"
	download file from "%{_link}%/manager/data.yml" to file "plugins/Skript/scripts/BCK/manager/data.yml"

	download file from "%{_link}%/manager/money/bck_money.sk" to file "plugins/Skript/scripts/BCK/manager/money/bck_money.sk"
	download file from "%{_link}%/manager/money/config.yml" to file "plugins/Skript/scripts/BCK/manager/money/config.yml"
	download file from "%{_link}%/manager/money/data.yml" to file "plugins/Skript/scripts/BCK/manager/money/data.yml"
	download file from "%{_link}%/manager/money/func.sk" to file "plugins/Skript/scripts/BCK/manager/money/func.sk"

	download file from "%{_link}%/manager/account/bck_account.sk" to file "plugins/Skript/scripts/BCK/manager/account/bck_account.sk"
	download file from "%{_link}%/manager/account/config.yml" to file "plugins/Skript/scripts/BCK/manager/account/config.yml"
	download file from "%{_link}%/manager/account/data.yml" to file "plugins/Skript/scripts/BCK/manager/account/data.yml"

	download file from "%{_link}%/manager/clan/bck_clan.sk" to file "plugins/Skript/scripts/BCK/manager/clan/bck_clan.sk"
	download file from "%{_link}%/manager/clan/config.yml" to file "plugins/Skript/scripts/BCK/manager/clan/config.yml"
	download file from "%{_link}%/manager/clan/data.yml" to file "plugins/Skript/scripts/BCK/manager/clan/data.yml"

	download file from "%{_link}%/manager/contener/bck_contener.sk" to file "plugins/Skript/scripts/BCK/manager/contener/bck_contener.sk"
	download file from "%{_link}%/manager/contener/config.yml" to file "plugins/Skript/scripts/BCK/manager/contener/config.yml"
	download file from "%{_link}%/manager/contener/data.yml" to file "plugins/Skript/scripts/BCK/manager/contener/data.yml"

	download file from "%{_link}%/manager/elevator/bck_elevator.sk" to file "plugins/Skript/scripts/BCK/manager/elevator/bck_elevator.sk"
	download file from "%{_link}%/manager/elevator/config.yml" to file "plugins/Skript/scripts/BCK/manager/elevator/config.yml"
	download file from "%{_link}%/manager/elevator/data.yml" to file "plugins/Skript/scripts/BCK/manager/elevator/data.yml"

	download file from "%{_link}%/manager/hammer/bck_hammer.sk" to file "plugins/Skript/scripts/BCK/manager/hammer/bck_hammer.sk"
	download file from "%{_link}%/manager/hammer/config.yml" to file "plugins/Skript/scripts/BCK/manager/hammer/config.yml"
	download file from "%{_link}%/manager/hammer/data.yml" to file "plugins/Skript/scripts/BCK/manager/hammer/data.yml"
	wait 0.5 seconds
	delete file "plugins/Skript/scripts/bck_installer.sk"
	unload script file "bck_installer.sk"
	wait 0.5 seconds
	make console execute command "/sk reload scripts"
	wait 1 seconds
	send "§6[§4BCK§6]§r Finish..." to console
	wait 0.2 second
	
	stop