command /copy <text>:
    trigger:
        # Insertion: when the player shift clicks on the message, it will add the text to their text box.
        # To use variables and other expressions with these tags, you have to send the text as `formatted`.
        formatted(arg-1, player)
command /suggest:
    trigger:
        send "<cmd:/me Bruh>Click here to run the command /say hi"
        send "<sgt:/say hi>Click here to suggest the command /say hi"