command /ride [<player>] [<player>]:
    trigger:
        if hasPermission(player, "server.command.ride") is false:
            send "§c§lHey! §7Tu n'a pas la permission :|"
            stop
        if arg-1 is set:
            if arg-2 is not set:
                make player ride arg-1
            else if arg-2 is player:
                make arg-1 ride arg-2
            else:
                send "§cIs not player !"
        else:
            send "§cEnter Player !"