on load:
    set {_list::*} to {skripts::*}
    if {_list::*} contains "bck_manager.sk":
        send "§6[§4BCK§6]§r Loading turret..." to console
        send "§6[§4BCK§6/§eTurret§6]§r Loaded successfully !" to console
        load yaml "plugins/Skript/scripts/BCK/manager/turret/config.yml" as "bck.manager.turret.config"
        load yaml "plugins/Skript/scripts/BCK/manager/turret/data.yml" as "bck.manager.turret.data"
    else:
        broadcast "§6[§4BCK§6/§eTurret§6]§r Script loading cancel It requires (bck_manager.sk)"
        unload script file "bck_turret.sk"