on load:
    if {skripts::*} contains "bck_core.sk" and "core.sk":
        send "§6[§4BCK§6]§r Loading contener..." to console
        send "§6[§4BCK§6/§3Contener§6]§r Loaded successfully !" to console
        load yaml "plugins/Skript/scripts/BCK/manager/contener/config.yml" as "bck.manager.contener.config"
        load yaml "plugins/Skript/scripts/BCK/manager/contener/data.yml" as "bck.manager.contener.data"
    else:
        broadcast "§6[§4BCK§6/§3Contener§6]§r Script loading cancel It requires (§lcore.sk§r and §lbck_manager.sk§r)"
        unload script file "bck_clan.sk"