data:
    drawer:
        line: "&8&m---⟮&r"
        uline: "&8&m⟯---&r"
        price: 1000
    bank:
        line: "&8&m---&r"
        price: 1000
    xpbank:
        line: "&8&m---⟮&r"
        uline: "&8&m⟯---&r"
        price: 1000
    config:
        compactDrawer: true
        compactDrawerItem: chest
        compactDrawerName: "§6Compact Drawer"
        compactDrawerLore:
            line1: "&7Type &6: &a"
            line2: "&7Quantité &6: &a"