data:
    money: "₣"
    gui:
        title: "§4§lBCK Manager"
        size: 5
        config:
            size: 3
            install:
                item: minecart
                name: "§2§lInstaller"
                needInstallLore: "§7Prêt à l'installation"
                desactivatedLore: "§7Désactivé"
                alreadyInstalledLore: "§7Déja installer"
            switch:
                item: lever
                name: "§6§lActivé/Désactivé"
                activatedLore: "§eEtat: §aActivé"
                desactivatedLore: "§eEtat: §cDésactivé"
                notInstalledLore: "§eEtat: §7Non Installé"
            uninstall:
                item: tnt
                name: "§4§lDésinstaller"
                needInstallLore: "§7Doit être installer"
            other:
                item: book
            userdata:
                item: player head
            recipe:
                giveLore: "§aLeft click to give"
        account:
            item: writable book
            name: "§d⟪ Account ⟫"
            guiName: "§dAccount"
            lore:
        box:
            item: ender chest
            name: "§1⟪ Box ⟫"
            guiName: "§1Box"
            lore:
        clan:
            item: player head
            name: "§1⟪ Clan ⟫"
            guiName: "§1Clan"
            lore:
        contener:
            item: chest
            name: "§3⟪ Contener ⟫"
            guiName: "§3Contener"
            lore:
        elevator:
            item: red wool
            name: "§7⟪ Elevator ⟫"
            guiName: "§7Elevator"
            lore:
        hammer:
            item: netherite pickaxe
            name: "§8⟪ Hammer ⟫"
            guiName: "§8Hammer"
            lore:
        mob:
            item: zombie head
            name: "§a⟪ Mob ⟫"
            guiName: "§aMob"
            lore:
        money:
            item: paper
            name: "§b⟪ Money ⟫"
            guiName: "§bMoney"
            lore:
        other:
            item: feather
            name: "§f⟪ Other ⟫"
            guiName: "§fOther"
            lore:
            - "§fOther System.."
        recipe:
            item: knowledge book
            name: "§a⟪ Recipe ⟫"
            guiName: "§aRecipe"
            lore:
            - "§aRecipe System.."
        userdata:
            item: name tag
            name: "§e⟪ Userdata ⟫"
            guiName: "§eUserdata"
            lore:
            - "§fUsers Database"
        zones:
            item: brick wall
            name: "§2⟪ Zones ⟫"
            guiName: "§2Zones"
            lore: