on load:
    set {_list::*} to {skripts::*}
    if {_list::*} contains "bck_manager.sk":
        send "§6[§4BCK§6]§r Loading attributs..." to console
        send "§6[§4BCK§6/§9Attributs§6]§r Loaded successfully !" to console
        load yaml "plugins/Skript/scripts/BCK/manager/attributs/config.yml" as "bck.manager.attributs.config"
        load yaml "plugins/Skript/scripts/BCK/manager/attributs/data.yml" as "bck.manager.attributs.data"
    else:
        broadcast "§6[§4BCK§6/§9Attributs§6]§r Script loading cancel It requires (bck_manager.sk)"
        unload script file "bck_attributs.sk"